name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install Ruby gems
        run: bundle install

      - name: Install Yarn packages
        run: bin/yarn

      - name: Set up database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run RSpec tests
        run: bin/rspec
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: Run Jest tests
        run: yarn test